Masked exfat-linux because the ebuild is failing past the compile stage.
FileNotFoundError: [Errno 2] No such file or directory: b'exfat.'

The exfat.ko ends up in ${S} so I'm not entirely sure where I'm going wrong with this